services:
  # Spark -----------
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./app_spark:/app
      - ./app_spark/conf/log4j2.properties:/spark/conf/log4j2.properties
    environment:
      - INIT_DAEMON_STEP=setup_spark
    entrypoint: "cd /app && pip install -r requirements.txt && /spark/bin/spark-submit ./consumer.py"

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

volumes:
  datanode: